services:
  selenium:
    image: selenium/standalone-firefox:latest
    platform: linux/arm64
    container_name: rsm-selenium
    environment:
      - SELENIUM_PORT=4444
    networks:
      - rsm-genai

networks:
  rsm-genai:
    name: rsm-genai
